events = [
    {
        "summary": "Project Meeting",
        "description": "Discuss project milestones and deliverables.",
        "location": "Conference Room A",
        "start": "10:00",
        "end": "11:00",
        "start_date": "2024-08-19",
        "end_date": "2024-10-07",
        "uid": "uid1@example.com",
        "status": "CONFIRMED",
        "sequence": 0,
        "frequency": "WEEKLY",
        "byday": ["MO", "WE"],
        "recurrence": 8,
        "attendees": ["mailto:johndoe@example.com"],
        "organizer": "mailto:jane.doe@example.com",
        "priority": 5,
        "categories": ["Meeting", "Work"],
        "color_id": "9",
        "hangout_link": "https://hangouts.google.com/call/abcdefg",
        "geo": "37.386013;-122.082932",
        "transp": "OPAQUE",
        "class": "PUBLIC",
        "attach": "http://example.com/agenda.pdf"
    },
    {
        "summary": "Morning Yoga",
        "description": "Daily morning yoga session.",
        "location": "Gym",
        "start": "07:00",
        "end": "08:00",
        "start_date": "2024-08-20",
        "end_date": "2024-10-09",
        "uid": "uid2@example.com",
        "status": "CONFIRMED",
        "sequence": 0,
        "frequency": "WEEKLY",
        "byday": ["TU", "TH", "SA"],
        "recurrence": 8,
        "attendees": ["mailto:janedoe@example.com"],
        "organizer": "mailto:johndoe@example.com",
        "priority": 3,
        "categories": ["Exercise", "Health"],
        "color_id": "5",
        "hangout_link": "https://hangouts.google.com/call/hijklmn",
        "geo": "40.712776;-74.005974",
        "transp": "OPAQUE",
        "class": "PUBLIC",
        "attach": "http://example.com/yoga.pdf"
    }
]